-- V1__baseline.sql
-- Baseline migration representing the schema as it already exists on RDS
-- (originally created by Hibernate ddl-auto=update). Flyway will be
-- "baselined" at this version, so this script itself will NOT be run
-- against the existing RDS database — it exists so that:
--   1) Anyone setting up a FRESH database (new environment, CI test DB,
--      a new teammate's local DB) can run Flyway from scratch and get
--      the exact same schema.
--   2) This file documents the schema state at the point Flyway took over.

CREATE TABLE app_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_of_birth date,
    email character varying(255) NOT NULL,
    gender smallint,
    name character varying(255),
    password character varying(255) NOT NULL,
    CONSTRAINT app_user_gender_check CHECK (((gender >= 0) AND (gender <= 2))),
    CONSTRAINT uk1j9d9a06i600gd43uu3km82jw UNIQUE (email)
);

CREATE TABLE hotel (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    active boolean NOT NULL,
    amenities text[],
    city character varying(255),
    address character varying(255),
    email character varying(255),
    location character varying(255),
    phone_number character varying(255),
    created_at timestamp(6) without time zone,
    name character varying(255) NOT NULL,
    photos text[],
    updated_at timestamp(6) without time zone,
    owner_id bigint,
    CONSTRAINT fkdihygcg12c598wu6e18l5sd0t FOREIGN KEY (owner_id) REFERENCES app_user(id)
);

CREATE TABLE room (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amenities text[],
    base_price numeric(10,2) NOT NULL,
    capacity integer NOT NULL,
    created_at timestamp(6) without time zone,
    photos text[],
    total_count integer NOT NULL,
    type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    hotel_id bigint NOT NULL,
    CONSTRAINT fkdosq3ww4h9m2osim6o0lugng8 FOREIGN KEY (hotel_id) REFERENCES hotel(id)
);

CREATE TABLE hotel_min_price (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    date date NOT NULL,
    price numeric(10,2) NOT NULL,
    updated_at timestamp(6) without time zone,
    hotel_id bigint NOT NULL,
    CONSTRAINT fkne8dgpjep57pvqfiv4g1c7nch FOREIGN KEY (hotel_id) REFERENCES hotel(id)
);

CREATE TABLE inventory (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booked_count integer DEFAULT 0 NOT NULL,
    city character varying(255) NOT NULL,
    closed boolean NOT NULL,
    created_at timestamp(6) without time zone,
    date date NOT NULL,
    price numeric(10,2) NOT NULL,
    reserved_count integer DEFAULT 0 NOT NULL,
    surge_factor numeric(5,2) NOT NULL,
    total_count integer NOT NULL,
    updated_at timestamp(6) without time zone,
    hotel_id bigint NOT NULL,
    room_id bigint NOT NULL,
    CONSTRAINT unique_hotel_room_data UNIQUE (hotel_id, room_id, date),
    CONSTRAINT fk81iasgjh573hbsoluoj670bkj FOREIGN KEY (hotel_id) REFERENCES hotel(id),
    CONSTRAINT fkkkm00xm4as7hupix7tlg0q3of FOREIGN KEY (room_id) REFERENCES room(id)
);

CREATE TABLE guest (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    age integer,
    gender character varying(255),
    name character varying(255) NOT NULL,
    user_id bigint,
    CONSTRAINT guest_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT fkdg6lwhvpl89f1yt2i40pbfiiy FOREIGN KEY (user_id) REFERENCES app_user(id)
);

CREATE TABLE booking (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(10,2) NOT NULL,
    booking_status character varying(255) NOT NULL,
    check_in_date date NOT NULL,
    check_out_date date NOT NULL,
    created_at timestamp(6) without time zone,
    rooms_count integer NOT NULL,
    updated_at timestamp(6) without time zone,
    hotel_id bigint NOT NULL,
    room_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT booking_booking_status_check CHECK (((booking_status)::text = ANY ((ARRAY['RESERVED'::character varying, 'GUESTS_ADDED'::character varying, 'PAYMENTS_PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying, 'EXPIRED'::character varying])::text[]))),
    CONSTRAINT fkhacdq9bfa3r9xdimovsnonbyi FOREIGN KEY (hotel_id) REFERENCES hotel(id),
    CONSTRAINT fkq83pan5xy2a6rn0qsl9bckqai FOREIGN KEY (room_id) REFERENCES room(id),
    CONSTRAINT fkn7phgawjwo673xgim9d2cvfe1 FOREIGN KEY (user_id) REFERENCES app_user(id)
);

CREATE TABLE booking_guest (
    booking_id bigint NOT NULL,
    guest_id bigint NOT NULL,
    CONSTRAINT booking_guest_pkey PRIMARY KEY (booking_id, guest_id),
    CONSTRAINT fkngrkuwlsaqjwe4mycjdvhuwtk FOREIGN KEY (booking_id) REFERENCES booking(id),
    CONSTRAINT fkbidkmu7pdnm82qpo2r3n699yd FOREIGN KEY (guest_id) REFERENCES guest(id)
);

CREATE TABLE payment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount numeric(10,2) NOT NULL,
    created_at timestamp(6) without time zone,
    payment_status character varying(255) NOT NULL,
    razorpay_payment_id character varying(255),
    razorpay_signature character varying(255),
    transaction_id character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    booking_id bigint,
    CONSTRAINT payment_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['CREATED'::character varying, 'PAID'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[]))),
    CONSTRAINT ukku02qy6369hn9uhy3n7jk9v6e UNIQUE (booking_id),
    CONSTRAINT uktacis04bqalsngo46yvxlo7yb UNIQUE (transaction_id),
    CONSTRAINT fkqewrl4xrv9eiad6eab3aoja65 FOREIGN KEY (booking_id) REFERENCES booking(id)
);

CREATE TABLE user_roles (
    user_id bigint NOT NULL,
    role character varying(255),
    CONSTRAINT user_roles_role_check CHECK (((role)::text = ANY ((ARRAY['GUEST'::character varying, 'HOTEL_MANAGER'::character varying])::text[]))),
    CONSTRAINT fk6fql8djp64yp4q9b3qeyhr82b FOREIGN KEY (user_id) REFERENCES app_user(id)
);