version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
  build:
    commands:
      - echo "Building the Spring Boot application..."
      - cd airbnb
      - chmod +x mvnw
      - ./mvnw clean package -DskipTests
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - airbnb/target/airbnb-0.0.1-SNAPSHOT.jar
    - airbnb/Procfile
  discard-paths: yes